game_order = [0]
game_description = "欢迎使用北理网协2025百团招新终端操作小游戏！"

[[command_hints]]
name = "ls"
hint = "列出工作目录下的所有文件"

[[command_hints]]
name = "cd"
hint = "改变工作目录"

[[command_hints]]
name = "echo"
hint = "向终端打印文字"

[[commmand_hints]]
name = "pwd"
hint = "Print working directory"

[[game]]
id = 0
description = "第一个游戏用于练习查看目录中的文件以及目录间切换"
available_command = ["ls", "cd", "echo", "pwd"]
environment = { dir = "set1", restore = true }

[[game.game_item]]
description = "你现在需要知道当前目录下有什么文件"
hint = "可以使用命令'ls'来列出当前目录下的文件！"
hint_command = ["ls"]
goal = { kind = "command_executed", expectation = ["ls", "ls -a"] }

[[game.game_item]]
description = "请进入名字最长的文件夹！"
hint = "使用'cd'命令来切换当前所在目录。比如'cd a'可以进入名为a的文件夹"
hint_command = ["cd"]
goal = { kind = "dir_entered", expectation = ["BITNP"]}  # MAKE SURE that the longest-name folder is BITNP

[[game.game_item]]
description = """真棒！让我们看看当前文件夹下有没有叫做“Miss. Shu Meiniang”的文件，然后告诉使用“true”或者“false”告诉中终端！"""
hint = "要想知道当前目录下有什么文件，可以使用指令'ls'；要想给终端打印一些消息，请使用指令'echo'，比如'echo a'就打印一个a给终端"
hint_command = ["ls", "echo"]
goal = { kind = "stdout", expectation = ["true"]}
